version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/SignalingServer
 hooks:
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 300
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 300
